# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  database: test_engines_db
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
 <<: *default
 encoding: unicode
 username: postgres
 password: postgres
 host: localhost
 port: 5432
 database: test_engines_db_test


production:
  <<: *default
  database: test_engines_db
